<!DOCTYPE html>
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page isErrorPage="true" %>
<%@ page import="com.webratio.struts.exceptions.ErrorInterpreter" %>
<%@ taglib prefix="html" uri="http://struts.apache.org/tags-html" %>
<%
ErrorInterpreter interpreter = new ErrorInterpreter(request);
%>
<html>
<head>
  <title>Error</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="BootstrapStyle/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="BootstrapStyle/css/app.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="BootstrapStyle/assets/js/html5shiv.js"></script>
		<script src="BootstrapStyle/assets/js/respond.min.js"></script>
	<![endif]-->	
</head>
<body>
<div class="container">

	<div class="page-header">
		<h1>An error occurred</h1>
		<p class="lead"><%=interpreter.getMessage(ErrorInterpreter.XML_FORMAT)%></p>
    </div>
    
    <% if (interpreter.hasOccurred()) { %>
		<h3>Occurred on:</h3>
		<p><%=interpreter.getOccurred()%></p>
	<% } %>
	<% if (interpreter.hasDetails()) { %>
		<h3>Details:</h3>
		<ul>
		<% for (java.util.Iterator it = interpreter.getDetails(ErrorInterpreter.XML_FORMAT).iterator(); it.hasNext(); ) { %>
			<li><%=it.next()%></li>
		<% } %>
		</ul>
	<% } %>
	<% if (interpreter.hasFixes()) { %>
		<h3>Suggestions:</h3>
		<ul>
		<% for (java.util.Iterator it = interpreter.getFixes(ErrorInterpreter.XML_FORMAT).iterator(); it.hasNext(); ) { %>
			<li><%=it.next()%></li>
		<% } %>
		</ul>
	<% } %>
	<!--
	<%=interpreter.getExceptionStackTrace(ErrorInterpreter.XML_FORMAT)%>
	-->
	<hr/>
	<footer>
		<p class="text-center">Generated by <a href="http://www.webratio.com" target="_blank" title="High Productivity Web and Mobile App Dev Platform">WebRatio<sup>&reg;</sup></a></p>
	</footer>
</div>
</body>
</html> 
